#!/bin/sh

# Copyright 2008-2019 Douglas Wikstrom
#
# This file is part of Verificatum Mix-Net (VMN).
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use, copy,
# modify, merge, publish, distribute, sublicense, and/or sell copies
# of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
# ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

###########################################################################
######################## Execute Demonstration. ###########################
###########################################################################

condverify() {
    set +e
    if test $CORRECTNESS = "noninteractive";
    then
	./verify || exit $?
    fi
    set -e
}

condprecomp() {
    set +e
    if test x${MAX_NO_CIPHERTEXTS} != x;
    then
	./precomp || exit $?
    fi
    set -e
}

checkreject() {

    if test x`grep reject mydemodir/Party01/dir/log` != x;
    then
	printf "\nSomebody rejected a proof!\n\n"
    fi
}

prifdef() {
    printf "$1=$2\n"
}

dumpparams() {

    printf "Parameters of check: $CHECK\n\n"

    prifdef NO_MIXSERVERS $NO_MIXSERVERS
    prifdef THRESHOLD $THRESHOLD
    prifdef MAX_NO_CIPHERTEXTS $MAX_NO_CIPHERTEXTS
    prifdef FORCED_MAX_NO_CIPHERTEXTS $FORCED_MAX_NO_CIPHERTEXTS
    prifdef NO_CIPHERTEXTS $NO_CIPHERTEXTS
    prifdef PGROUP "$PGROUP"
    prifdef CORRECTNESS $CORRECTNESS
    prifdef WIDTH $WIDTH
    prifdef KEYWIDTH $KEYWIDTH
    prifdef FORCED_WIDTH $FORCED_WIDT
    prifdef INTER $INTER
    prifdef HASH $HASH
    prifdef SIG $SIG
    prifdef PRG $PRG
    prifdef RAND $RAND
    prifdef ARRAYS $ARRAYS
    printf "\n"
}

CHECKS="threshold1 thresholdlarge manyciphs maxciph forcedmaxciph fixed interactive width forcedwidth keywidth31 keywidth32 raw json jsondecode provablehash provableprg provablerandsrc heuristicrandsrc ram"

printf "
###########################################################################

           CHECKING COMMAND-LINE EXECUTION OF MIX-NET

 Please be very patient. This check may take a long time. It iterates
 through a large number of different configurations of the mix-net and
 for each configuration we use the mix-net to mix ciphertexts, to
 shuffle ciphertexts without decrypting, and to decrypt ciphertexts
 without shuffling. Keep in mind that a mix-net is a multiparty
 protocol.
\n
"

for CHECK in $CHECKS;
do
    printf "###########################################################################\n\n"
    printf "CHECK=$CHECK" > conf
    cat .checkbaseconf >> conf

    . ./conf

    dumpparams

    set -e

    # Check mixing.
    ./clean
    ./info_files
    ./keygen
    ./gen_ciphs
    condprecomp
    ./mix
    condverify
    checkreject

    # Check shuffling.
    ./delete
    condprecomp
    ./shuffle
    condverify
    checkreject

    # Check decryption.
    ./delete
    ./decrypt
    condverify
    checkreject

    # Check shuffling with imported public key.
    ./clean
    ./info_files
    ./setpk
    ./gen_ciphs
    condprecomp
    ./shuffle
    condverify

    checkreject

    set +e

    printf "\n"

done
