#!/bin/sh

# Copyright 2008-2019 Douglas Wikstrom
#
# This file is part of Verificatum Mix-Net (VMN).
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use, copy,
# modify, merge, publish, distribute, sublicense, and/or sell copies
# of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
# ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Make sure we log everything.
{

. ./macros

phasestart "Cleaning up data from previous demos"

if test ! -f ./conf;
then
    ./restore
fi

. ./conf 2> /dev/null

find . -name "*~" -delete
rm -rf pGroup $TMP_COMMAND publicKey export* progress active_mixservers exitcode

for i in `seq 1 $NO_MIXSERVERS`;
do
    rmfrat "${i}"
done

phaseend

rm -f demo_log
rm -f vmnv_log
rm -f vmn_log

rm -f complete_demo_log
rm -f complete_vmnv_log
rm -f complete_vmn_log


# Make sure we log everything.
} | tee -a demo_log
