#!/bin/sh

# Copyright 2008-2018 Douglas Wikstrom
#
# This file is part of Verificatum Mix-Net (VMN).
#
# VMN is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# VMN is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General
# Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with VMN. If not, see <http://www.gnu.org/licenses/>.

# Make sure we log everything.
{

. ./macros

phasestart "Cleaning up data from previous demos"

if test ! -f ./conf;
then
    ./restore
fi

. ./conf 2> /dev/null

find . -name "*~" -delete
rm -rf pGroup $TMP_COMMAND publicKey export* progress active_mixservers exitcode

for i in `seq 1 $NO_MIXSERVERS`;
do
    rmfrat "${i}"
done

phaseend

rm -f demo_log
rm -f vmnv_log
rm -f vmn_log

rm -f complete_demo_log
rm -f complete_vmnv_log
rm -f complete_vmn_log


# Make sure we log everything.
} | tee -a demo_log
