#!/bin/sh

# Copyright 2008-2019 Douglas Wikstrom
#
# This file is part of Verificatum Mix-Net (VMN).
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use, copy,
# modify, merge, publish, distribute, sublicense, and/or sell copies
# of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
# ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

###########################################################################
####################### Execute key generation. ###########################
###########################################################################

# Make sure we log everything.
{

. ./checkvmn

. ./conf

phasestart "Deleting previous session"

for i in `seq 1 $NO_MIXSERVERS`
do

    printf "vmn -delete -e $SILENT -f; printf \$? > exitcode" > $TMP_COMMAND
    cpevalat $TMP_COMMAND $i

    wait
    checkexit $i

done

# Wait until all servers have completed.
wait

if test $CORRECTNESS = "noninteractive"
then

    printf "rm -rf export/default" > $TMP_COMMAND
    cpevalat $TMP_COMMAND 1

    checkexit 1
    wait

fi

rm -rf export/*

phaseend

# Make sure we log everything.
} | tee -a demo_log
