#!/bin/sh

# Copyright 2008-2019 Douglas Wikstrom
#
# This file is part of Verificatum Mix-Net (VMN).
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use, copy,
# modify, merge, publish, distribute, sublicense, and/or sell copies
# of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
# ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Make sure we log everything.
{

. ./checkvmn

. ./conf

phasestart "Generate demo ciphertexts"

if test "x${1}" = "x";
then
    if test "x$FORCED_WIDTH" = "x"
    then
	widthcom WIDTHCOM $WIDTH
    else
	widthcom WIDTHCOM $FORCED_WIDTH
    fi
else
    widthcom WIDTHCOM ${1}
fi

# Party01 generates list of ciphertexts.
printf "
vmnd -ciphs -e -i $INTER $WIDTHCOM publicKey_ext $NO_CIPHERTEXTS ciphertexts_ext && vmnc -ciphs -sloppy -ini $INTER $WIDTHCOM ciphertexts_ext ciphertexts
printf \$? > exitcode
" > $TMP_COMMAND
cpevalat $TMP_COMMAND 1

checkexit 1

phaseend
phasestart "Copy demo ciphertexts to parties"

# Copy list of ciphertexts to all parties.
for i in `seq 2 $NO_MIXSERVERS`
do
    copyfromto ciphertexts 1 $i
done

wait

phaseend

# Make sure we log everything.
} | tee -a demo_log
