#!/bin/sh

# Copyright 2008-2018 Douglas Wikstrom
#
# This file is part of Verificatum Mix-Net (VMN).
#
# VMN is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# VMN is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General
# Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with VMN. If not, see <http://www.gnu.org/licenses/>.

# Make sure we log everything.
{

. ./checkvmn

. ./conf

phasestart "Generate demo ciphertexts"

if test "x${1}" = "x";
then
    if test "x$FORCED_WIDTH" = "x"
    then
	widthcom WIDTHCOM $WIDTH
    else
	widthcom WIDTHCOM $FORCED_WIDTH
    fi
else
    widthcom WIDTHCOM ${1}
fi

# Party01 generates list of ciphertexts.
printf "
vmnd -ciphs -e -i $INTER $WIDTHCOM publicKey_ext $NO_CIPHERTEXTS ciphertexts_ext && vmnc -ciphs -sloppy -ini $INTER $WIDTHCOM ciphertexts_ext ciphertexts
printf \$? > exitcode
" > $TMP_COMMAND
cpevalat $TMP_COMMAND 1

checkexit 1

phaseend
phasestart "Copy demo ciphertexts to parties"

# Copy list of ciphertexts to all parties.
for i in `seq 2 $NO_MIXSERVERS`
do
    copyfromto ciphertexts 1 $i
done

wait

phaseend

# Make sure we log everything.
} | tee -a demo_log
