#!/bin/sh

# Copyright 2008-2018 Douglas Wikstrom
#
# This file is part of Verificatum Mix-Net (VMN).
#
# VMN is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# VMN is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General
# Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with VMN. If not, see <http://www.gnu.org/licenses/>.

###########################################################################
########################### Set public key. ###############################
###########################################################################

# Make sure we log everything.
{

. ./checkvmn

. ./conf

phasestart "Importing external public key into mix-servers"

keywidthcom KEYWIDTHCOM $KEYWIDTH

# Generate a demo public key and copy it to all servers.
evalat "vmnd -pkey -e -i $INTER $KEYWIDTHCOM \"$PGROUP\" publicKey_ext && vmnc -pkey -ini $INTER publicKey_ext publicKey; printf \$? > exitcode" 1

wait
checkexit 1

for i in `seq 2 $NO_MIXSERVERS`
do
    copyfromto publicKey 1 $i
    copyfromto publicKey_ext 1 $i
done


for i in `seq 1 $NO_MIXSERVERS`
do
    evalat "vmn -setpk -e $SILENT publicKey; printf \$? > exitcode" $i
done

# Wait until all servers have completed.
wait

checkallexits

phaseend

# Make sure we log everything.
} | tee -a demo_log
