#!/bin/sh

# Copyright 2008-2019 Douglas Wikstrom
#
# This file is part of Verificatum Mix-Net (VMN).
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use, copy,
# modify, merge, publish, distribute, sublicense, and/or sell copies
# of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
# ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

###########################################################################
################### Execute standalone verifier. ##########################
###########################################################################

. ./checkvmn

. ./conf

if test x$AUXSID = x;
then
    AUXSIDDIR=default
else
    AUXSIDDIR=$AUXSID
fi

if test x$SILENT = x;
then
    VERBOSE=-v
else
    VERBOSE=
fi

# Make sure we log everything.
{

if test $CORRECTNESS = "noninteractive"
then

    phasestart "Copying proof from Party01 (verifier is not executing yet)"

    printf "
rm -rf export
mkdir export
cd export
cp -R ../dir/nizkp/$AUXSIDDIR .
cp ../protInfo.xml .
cd ..
" > $TMP_COMMAND

    cpevalat $TMP_COMMAND 1

    rm -rf export
    copyfrom 1 export .

    phaseend

    phasestart "Verify Fiat-Shamir Proof"

    # Make sure we log everything.
    {

	printf "\n"

	vmnv -sloppy $VERBOSE -v -e -wd "/tmp/verificatum/$$" -a $ARRAYS export/protInfo.xml export/$AUXSIDDIR

	EXITCODE=$?
	rm -rf "/tmp/verificatum/$$"

	test $EXITCODE = 0 || exit $EXITCODE

    # Make sure we log everything.
    } >> vmnv_log

    phaseend

else

    printf "\nERROR!"
    printf "You can not verify an execution that used *interactive* "
    printf "zero-knowledge proofs. Please edit the CORRECTNESS variable"
    printf "in the conf-file to try out *non-interactive* proofs in the"
    printf "random oracle model.\n\n"

fi

# Make sure we log everything.
} | tee -a demo_log

